words = ('abbas', 'abstergo', 'accipio', 'acquiro', 'adepto', 'adinventitias',
        'adnuo', 'adulescens', 'aeger', 'aer', 'agnitio', 'alioqui', 'aliquis',
        'alter', 'amissio', 'an', 'annus', 'appareo', 'apud', 'arcesso',
        'articulus', 'asporto', 'atrox', 'audax', 'aut', 'avoco', 'bene',
        'blesense', 'cado', 'callidus', 'capitulus', 'carnotense', 'catervatim',
        'cavus', 'cena', 'certus', 'cicuta', 'civis', 'claustrum', 'cognosco',
        'colo', 'cometissa', 'comminus', 'commoveo', 'compes', 'comprehendo',
        'concilium', 'condico', 'congrego', 'conscendo', 'consisto', 'consto',
        'consulatio', 'consuo', 'contemplor', 'contigo', 'contradictio',
        'copia', 'corroboro', 'crastinus', 'creta', 'crur', 'cui', 'cum',
        'cupido', 'curiosus', 'cursor', 'damnatio', 'decimus', 'deduco',
        'defluo', 'delego', 'demitto', 'denuntio', 'deprecor', 'desidiosus',
        'despicio', 'devito', 'dictito', 'differtus', 'dilabor', 'directus',
        'dispono', 'districtus', 'divinitus', 'dolor', 'donec', 'dudum',
        'dusiol', 'edo', 'egenus', 'eligo', 'emineo', 'episcopalis', 'erga',
        'erudio', 'evito', 'excludo', 'exesto', 'eximietate', 'exorsus',
        'expiscor', 'expugno', 'externus', 'fabula', 'facundia', 'fas', 'felix',
        'festinatio', 'fiducia', 'flamma', 'forma', 'fortuna', 'frequentia',
        'frustra', 'fundo', 'galea', 'gestum', 'gratia', 'gregatim', 'haec',
        'hesito', 'his', 'homo', 'hos', 'humanitas', 'iaculator', 'ideo',
        'illa', 'ille', 'illis', 'illorum', 'imcomposite', 'immunda', 'impendo',
        'impleo', 'impudenter', 'incertus', 'inconsulte', 'inde', 'induco',
        'infectum', 'inferi', 'inficio', 'infirmatio', 'inflammo', 'infligo',
        'infra', 'iniquus', 'inquis', 'inservio', 'instar', 'insurgo',
        'interdico', 'intumesco', 'invetero', 'iocus', 'is', 'iucunditas',
        'ius', 'jugis', 'labiosus', 'labrum', 'lacesso', 'lacto', 'laetatio',
        'lama', 'laqueus', 'lectica', 'lemures', 'lentesco', 'lepor', 'levamen',
        'levo', 'liberaliter', 'ligo', 'loci', 'loricatus', 'ludus', 'macero',
        'madidus', 'maiores', 'mandatum', 'maritus', 'medicus', 'memor',
        'mereo', 'miles', 'minuo', 'missa', 'modus', 'monasteriense', 'morbus',
        'mucro', 'mundus', 'muto', 'natura', 'necne', 'neque', 'nimirum',
        'niveus', 'nomine', 'noster', 'nox', 'nusquam', 'obligatus', 'obviam',
        'odio', 'omnipotens', 'oportet', 'oppugno', 'ordinatio', 'otium',
        'pala', 'paratus', 'pars', 'paternus', 'pauper', 'peior', 'per',
        'perduco', 'periclitor', 'perperam', 'persolvo', 'pertingo', 'pes',
        'peto', 'piger', 'placet', 'platea', 'plorabilis', 'plura', 'poema',
        'pono', 'post', 'potior', 'praebeo', 'praecox', 'praemitto',
        'praesidium', 'praeterea', 'precipue', 'primo', 'pristinus', 'probitas',
        'prodigiosus', 'profiteor', 'progigno', 'proinde', 'prolixus',
        'promiscus', 'promptu', 'prope', 'proprius', 'protestor', 'proximus',
        'pudor', 'pugno', 'pulmo', 'pungo', 'purgo', 'putus', 'quadrum',
        'quaeso', 'quam', 'quanto', 'quantuvis', 'quatenus', 'querimonia',
        'quibus', 'quilibet', 'quisquis', 'quomodo', 'quovis', 'recognosco',
        'rectus', 'redeo', 'regina', 'reliquum', 'renuo', 'repletus',
        'respicio', 'revertor', 'rogo', 'rus', 'saeta', 'salvus', 'sano',
        'satio', 'sceleratus', 'scio', 'secundum', 'sedeo', 'sentio', 'serius',
        'si', 'silenti', 'simul', 'siquidem', 'solio', 'solum', 'sonitus',
        'spectaculum', 'spolio', 'statuo', 'studiose', 'subnecto', 'sufficio',
        'summopere', 'superna', 'supplex', 'suspendo', 'taceo', 'tametsi', 'te',
        'templovium', 'tener', 'tergeo', 'tero', 'texo', 'thermae', 'titulus',
        'toties', 'transeo', 'tricesimus', 'truculenter', 'turbatio', 'ubi',
        'una', 'urbs', 'ut', 'utpote', 'valde', 'vehementer', 'ventosus', 'vergo',
        'vesica', 'via', 'viduata', 'vindico', 'virtus', 'vobis', 'volo', 'voluptuosus',
        'vos', 'vulnus')
